name:                pymble
version:             0.1.0.0
github:              "weak-head/pymble"
license:             BSD3
author:              "Oleksandr Zinchenko"
maintainer:          "zinchenko@live.com"
copyright:           "2018 Oleksandr Zinchenko"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/weak-head/pymble#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src/
  dependencies:
  - data-default
  - network
  - network-uri
  - transformers
  - monad-loops
  - time
  - exceptions
  - JuicyPixels
  - http-conduit
  - http-types
  - repa
  - containers
  - vector-th-unbox
  - vector
  - optparse-applicative
  - directory

executables:
  pymble:
    main: Main.hs
    source-dirs: src/main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pymble
    - data-default
    - optparse-applicative

tests:
  pymble-test:
    main: Test.hs
    source-dirs: src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pymble
    - hspec
    - QuickCheck
    - containers
    - optparse-applicative