name:                pymble
version:             0.1.0.0
github:              "weak-head/pymble"
license:             BSD3
author:              "Oleksandr Zinchenko"
maintainer:          "zinchenko@live.com"
copyright:           "2018 Oleksandr Zinchenko"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/weak-head/pymble#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src/
  dependencies:
  - JuicyPixels
  - MissingH
  - bytestring
  - containers
  - data-default
  - directory
  - exceptions
  - http-conduit
  - http-types
  - megaparsec
  - monad-loops
  - network
  - network-uri
  - optparse-applicative
  - repa
  - time
  - transformers
  - vector
  - vector-th-unbox

executables:
  pymble:
    main: Main.hs
    source-dirs: src/main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pymble
    - data-default
    - exceptions
    - optparse-applicative

tests:
  pymble-test:
    main: Test.hs
    source-dirs: src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pymble
    - QuickCheck
    - bytestring
    - containers
    - hspec
    - megaparsec
    - optparse-applicative